services:
  komuzik-bot:
    build: .
    container_name: komuzik_bot_app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./session:/app/session
      - ./data:/app/data