[project]
name = "komuzik"
version = "0.1.0"
description = ""
authors = [{ name = "Kotaz", email = "semechkagent@gmail.com" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
dependencies = [
    "gallery-dl>=1.31.10",
    "pyrogram[asyncio]>=2.0.106",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "telethon>=1.42.0",
    "tgcrypto>=1.2.5",
    "yt-dlp>=2026.3.17",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
